-- One row per ledger account.
--
-- `balance` is a materialized derived aggregate. The ledger entries added in a later
-- migration are the canonical record; this column exists only so that reading a balance
-- does not have to scan the account's whole history. It is written exclusively inside the
-- same transaction as the entry that changes it, and is reconcilable at any time by
-- summing the entries.

CREATE TABLE accounts (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number  VARCHAR(20)    NOT NULL,
    owner_name      VARCHAR(120)   NOT NULL,
    currency        CHAR(3)        NOT NULL,
    balance         NUMERIC(19, 4) NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT uq_accounts_account_number       UNIQUE (account_number),
    CONSTRAINT ck_accounts_balance_non_negative CHECK (balance >= 0),
    CONSTRAINT ck_accounts_currency_iso_4217    CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_accounts_owner_name_not_blank CHECK (length(btrim(owner_name)) > 0)
);

COMMENT ON TABLE  accounts         IS 'Ledger accounts. One row per account.';
COMMENT ON COLUMN accounts.balance IS 'Materialized derived aggregate of the account''s ledger entries. Entries remain canonical.';
