-- A financial event, and the entries it produced.
--
-- One event (a deposit, a withdrawal, a transfer) creates exactly one `transactions` row and
-- one or more `ledger_entries` rows. A transfer produces two entries: a DEBIT on the source
-- account and a CREDIT on the destination. Grouping them under a transaction is what records
-- that they are two halves of the same event.
--
-- `ledger_entries` is APPEND-ONLY. Rows are never updated or deleted. A mistake is corrected by
-- posting a reversing entry, so the history always says what actually happened.

CREATE TABLE transactions (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference    UUID         NOT NULL,
    type         VARCHAR(12)  NOT NULL,
    description  VARCHAR(255),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- The idempotency key. A client that retries a request with the same reference cannot
    -- create the event twice: the second insert violates this constraint.
    CONSTRAINT uq_transactions_reference UNIQUE (reference),
    CONSTRAINT ck_transactions_type      CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER'))
);

CREATE TABLE ledger_entries (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  BIGINT         NOT NULL,
    account_id      BIGINT         NOT NULL,
    direction       VARCHAR(6)     NOT NULL,
    amount          NUMERIC(19, 4) NOT NULL,
    balance_after   NUMERIC(19, 4) NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_ledger_entries_transaction
        FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_ledger_entries_account
        FOREIGN KEY (account_id) REFERENCES accounts (id),

    -- Amount is always positive; `direction` says which way the money moved. Storing a signed
    -- amount would work too, but this makes every row readable without knowing the convention.
    CONSTRAINT ck_ledger_entries_direction      CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_ledger_entries_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_ledger_entries_balance_after_non_negative CHECK (balance_after >= 0)
);

-- PostgreSQL does not index foreign keys automatically. Both of these back real queries:
-- "the entries for this account, in order", and "the other side of this transfer".
CREATE INDEX ix_ledger_entries_account_id ON ledger_entries (account_id, id);
CREATE INDEX ix_ledger_entries_transaction_id ON ledger_entries (transaction_id);

COMMENT ON TABLE  ledger_entries               IS 'Append-only. Never updated or deleted; corrections are reversing entries.';
COMMENT ON COLUMN ledger_entries.balance_after IS 'The account balance immediately after this entry was applied.';
COMMENT ON COLUMN transactions.reference       IS 'Client-supplied idempotency key. Unique, so a retry cannot duplicate the event.';
